name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Navigate to recipeapp directory
      run: cd recipeapp

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
