name: Run Azure Login with OIDC
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs: 
  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Run az commands
        run: |
          az account show
          az group list

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: recipeapp/src
          acrName: recipeapp103
          containerAppName: recipeapp103
          resourceGroup: cosi-103
