name: run-tests
on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Repository Contents
        run: |
          ls -la
          cd cosi-103a
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd cosi-103a/recipeapp
          npm ci

      - name: Run Tests
        run: |
          cd cosi-103a/recipeapp
          npm test
